[package]
name = "dungeon_crawler"
version = "0.1.0"
edition = "2021"
authors = ["Andrey Agafonov <a.s.agafonov@yandex.ru>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rust-i18n = "2"
substring = "1.4.5"